### ISSUE TITLE
No module named Tkinter found

### ISSUE THREAD

**Issue by varunotelli** [shubhamc183/way2sms#3]
Getting error while  trying to send sms
`ModuleNotFoundError: No module named 'Tkinter'`

**Comment by shubhamc183** [comment]
You are getting this error because you don't have Tkinter package installed in your current python PATH.

In python2, it's **Tkinter**, whereas in python3 it's **tkinter**
```python
try:
    # for Python2
    from Tkinter import *   ## notice capitalized T in Tkinter 
except ImportError:
    # for Python3
    from tkinter import *   ## notice lowercase 't' in tkinter here
```

[Check here](https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter).

**BUT YOU DON'T NEED TKINTER FOR THIS PROGRAM TO RUN..!**, if you are doing something additional then try installing [using.](https://askubuntu.com/questions/505141/unable-to-install-import-tkinter)
